name: Simple Build Check

on:
  push:   # Runs whenever you push to the repo
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print success message
        run: echo "✅ Build ran successfully!"
        
